In [1]:
#Import numerical libraries
import pandas as pd
import numpy as np

#Import graphical plotting libraries
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

#Import Linear Regression Machine Learning Libraries
from sklearn import preprocessing
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import r2_score

In [3]:
data = pd.read_csv(r'C:\Users\vinay agrawal\FSDS_PROJECT\7th- l1, l2, scaling\7th- l1, l2, scaling\lasso, ridge, elastic net\TASK-22_LASSO,RIDGE/car-mpg.csv')
data.head()

,mpg,cyl,disp,hp,wt,acc,yr,origin,car_type,car_name
0,18.0,8,307.0,130,3504,12.0,70,1,0,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,0,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,0,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,0,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,0,ford torino

In [4]:
# Drop car_name
data = data.drop('car_name', axis=1)

# Replace origin values
data['origin'] = data['origin'].replace({
    1: 'america',
    2: 'europe',
    3: 'asia'
})

In [5]:
# One-hot encoding
data = pd.get_dummies(data, columns=['origin'])

In [6]:
# Replace ? with NaN
data = data.replace('?', np.nan)

In [7]:
# Convert hp to numeric
data['hp'] = pd.to_numeric(data['hp'], errors='coerce')

In [8]:
# Fill missing values with median
numeric_cols = data.select_dtypes(include='number').columns
data[numeric_cols] = data[numeric_cols].fillna(data[numeric_cols].median())

data.head()

,mpg,cyl,disp,hp,wt,acc,yr,car_type,origin_america,origin_asia,origin_europe
0,18.0,8,307.0,130.0,3504,12.0,70,0,True,False,False
1,15.0,8,350.0,165.0,3693,11.5,70,0,True,False,False
2,18.0,8,318.0,150.0,3436,11.0,70,0,True,False,False
3,16.0,8,304.0,150.0,3433,12.0,70,0,True,False,False
4,17.0,8,302.0,140.0,3449,10.5,70,0,True,False,False

In [ ]:
Model Building

In [12]:
X = data.drop(['mpg'], axis = 1) # independent variable
y = data[['mpg']] #dependent variable
print("Independent var\n",X)
print("Dependent variable \n",y)

Independent var
      cyl   disp     hp    wt   acc  yr  car_type  origin_america  origin_asia  \
0      8  307.0  130.0  3504  12.0  70         0            True        False
1      8  350.0  165.0  3693  11.5  70         0            True        False
2      8  318.0  150.0  3436  11.0  70         0            True        False
3      8  304.0  150.0  3433  12.0  70         0            True        False
4      8  302.0  140.0  3449  10.5  70         0            True        False
..   ...    ...    ...   ...   ...  ..       ...             ...          ...
393    4  140.0   86.0  2790  15.6  82         1            True        False
394    4   97.0   52.0  2130  24.6  82         1           False        False
395    4  135.0   84.0  2295  11.6  82         1            True        False
396    4  120.0   79.0  2625  18.6  82         1            True        False
397    4  119.0   82.0  2720  19.4  82         1            True        False

     origin_europe
0            False
1            False
2            False
3            False
4            False
..             ...
393          False
394           True
395          False
396          False
397          False

[398 rows x 10 columns]
Dependent variable
       mpg
0    18.0
1    15.0
2    18.0
3    16.0
4    17.0
..    ...
393  27.0
394  44.0
395  32.0
396  28.0
397  31.0

[398 rows x 1 columns]

In [13]:
#Scaling the data

X_s = preprocessing.scale(X)
X_s = pd.DataFrame(X_s, columns = X.columns) #converting scaled data into dataframe

y_s = preprocessing.scale(y)
y_s = pd.DataFrame(y_s, columns = y.columns) #ideally train, test data should be in columns

print("Scaled Data in dataframe \n",X_s)
print("Train and Test data in column as below \n",y_s)

Scaled Data in dataframe
           cyl      disp        hp        wt       acc        yr  car_type  \
0    1.498191  1.090604  0.673118  0.630870 -1.295498 -1.627426 -1.062235
1    1.498191  1.503514  1.589958  0.854333 -1.477038 -1.627426 -1.062235
2    1.498191  1.196232  1.197027  0.550470 -1.658577 -1.627426 -1.062235
3    1.498191  1.061796  1.197027  0.546923 -1.295498 -1.627426 -1.062235
4    1.498191  1.042591  0.935072  0.565841 -1.840117 -1.627426 -1.062235
..        ...       ...       ...       ...       ...       ...       ...
393 -0.856321 -0.513026 -0.479482 -0.213324  0.011586  1.621983  0.941412
394 -0.856321 -0.925936 -1.370127 -0.993671  3.279296  1.621983  0.941412
395 -0.856321 -0.561039 -0.531873 -0.798585 -1.440730  1.621983  0.941412
396 -0.856321 -0.705077 -0.662850 -0.408411  1.100822  1.621983  0.941412
397 -0.856321 -0.714680 -0.584264 -0.296088  1.391285  1.621983  0.941412

     origin_america  origin_asia  origin_europe
0          0.773559    -0.497643      -0.461968
1          0.773559    -0.497643      -0.461968
2          0.773559    -0.497643      -0.461968
3          0.773559    -0.497643      -0.461968
4          0.773559    -0.497643      -0.461968
..              ...          ...            ...
393        0.773559    -0.497643      -0.461968
394       -1.292726    -0.497643       2.164651
395        0.773559    -0.497643      -0.461968
396        0.773559    -0.497643      -0.461968
397        0.773559    -0.497643      -0.461968

[398 rows x 10 columns]
Train and Test data in column as below
           mpg
0   -0.706439
1   -1.090751
2   -0.706439
3   -0.962647
4   -0.834543
..        ...
393  0.446497
394  2.624265
395  1.087017
396  0.574601
397  0.958913

[398 rows x 1 columns]

In [14]:
#Split into train, test set

X_train, X_test, y_train,y_test = train_test_split(X_s, y_s, test_size = 0.30, random_state = 1)
X_train.shape

(278, 10)

In [ ]:
Simple Linear Model¶

In [15]:
#Fit simple linear model and find coefficients
regression_model = LinearRegression()
regression_model.fit(X_train, y_train)

for idx, col_name in enumerate(X_train.columns):
    print('The coefficient for {} is {}'.format(col_name, regression_model.coef_[0][idx]))
    
intercept = regression_model.intercept_[0]
print('The intercept is {}'.format(intercept))

The coefficient for cyl is 0.3210223856916096
The coefficient for disp is 0.32483430918483935
The coefficient for hp is -0.22916950059437635
The coefficient for wt is -0.7112101905072296
The coefficient for acc is 0.014713682764191155
The coefficient for yr is 0.3755811949510742
The coefficient for car_type is 0.38147694842330954
The coefficient for origin_america is -0.07472247547584211
The coefficient for origin_asia is 0.04451525203567797
The coefficient for origin_europe is 0.04834854953945393
The intercept is 0.019284116103639705

In [ ]:
Regularalised Ridge Regression

In [16]:
#alpha factor here is lambda (penalty term) which helps to reduce the magnitude of coeff

ridge_model = Ridge(alpha = 0.3)
ridge_model.fit(X_train, y_train)

print('Ridge model coef: {}'.format(ridge_model.coef_))
#As the data has 10 columns hence 10 coefficients appear here

Ridge model coef: [ 0.31649043  0.31320707 -0.22876025 -0.70109447  0.01295851  0.37447352
  0.37725608 -0.07423624  0.04441039  0.04784031]

In [ ]:
Regularized Lasso Regression

In [17]:
#alpha factor here is lambda (penalty term) which helps to reduce the magnitude of coeff

lasso_model = Lasso(alpha = 0.1)
lasso_model.fit(X_train, y_train)

print('Lasso model coef: {}'.format(lasso_model.coef_))
#As the data has 10 columns hence 10 coefficients appear here

Lasso model coef: [-0.         -0.         -0.01690287 -0.51890013  0.          0.28138241
  0.1278489  -0.01642647  0.          0.        ]