## Label Encoding

In [2]:
# Data Encoding for Data Transformation

In [3]:
from pandas import *

In [6]:
df = read_csv('encoding.csv')

In [7]:
df.head()

,Age,Salary,Experience,ProjectsCompleted,WorkHours,Education,PerformanceLevel,JobRole,City,Department,Label
0,27,123337,15,9,9.7,High School,Low,Manager,Bangalore,HR,0
1,26,81732,8,2,7.7,High School,Medium,Engineer,Bangalore,IT,0
2,22,129391,5,7,4.2,PhD,High,Engineer,Hyderabad,HR,1
3,56,112164,16,16,6.6,PhD,High,Consultant,Chennai,Finance,1
4,40,74316,4,29,4.6,Bachelor,High,Manager,Mumbai,HR,1

In [8]:
df.describe()

,Age,Salary,Experience,ProjectsCompleted,WorkHours,Label
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,40.296000,86404.052000,12.211000,25.130000,7.986800,0.217000
std,11.809566,36045.883045,7.353132,14.458913,2.315757,0.412409
min,20.000000,25089.000000,0.000000,1.000000,4.000000,0.000000
25%,30.000000,54418.500000,6.000000,13.000000,6.000000,0.000000
50%,41.000000,86760.000000,12.000000,25.000000,8.100000,0.000000
75%,50.000000,116801.000000,18.000000,38.000000,10.000000,0.000000
max,60.000000,149982.000000,25.000000,50.000000,12.000000,1.000000

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                1000 non-null   int64
 1   Salary             1000 non-null   int64
 2   Experience         1000 non-null   int64
 3   ProjectsCompleted  1000 non-null   int64
 4   WorkHours          1000 non-null   float64
 5   Education          1000 non-null   object
 6   PerformanceLevel   1000 non-null   object
 7   JobRole            1000 non-null   object
 8   City               1000 non-null   object
 9   Department         1000 non-null   object
 10  Label              1000 non-null   int64
dtypes: float64(1), int64(5), object(5)
memory usage: 86.1+ KB

In [12]:
df.select_dtypes(include='object').columns

Index(['Education', 'PerformanceLevel', 'JobRole', 'City', 'Department'], dtype='object')

In [15]:
df.dtypes

Age                    int64
Salary                 int64
Experience             int64
ProjectsCompleted      int64
WorkHours            float64
Education             object
PerformanceLevel      object
JobRole               object
City                  object
Department            object
Label                  int64
dtype: object

In [16]:
df.select_dtypes(include='object')

       Education PerformanceLevel     JobRole       City Department
0    High School              Low     Manager  Bangalore         HR
1    High School           Medium    Engineer  Bangalore         IT
2            PhD             High    Engineer  Hyderabad         HR
3            PhD             High  Consultant    Chennai    Finance
4       Bachelor             High     Manager     Mumbai         HR
..           ...              ...         ...        ...        ...
995          PhD              Low     Manager  Hyderabad         HR
996     Bachelor             High     Manager    Chennai    Finance
997       Master              Low     Manager  Bangalore         IT
998     Bachelor              Low  Consultant     Mumbai    Finance
999  High School           Medium    Engineer     Mumbai    Finance

[1000 rows x 5 columns]

In [31]:
# Display unique values

cat_cols = df.select_dtypes(include='object').columns
for cat in cat_cols:
    print(f"col name {cat} : {df[cat].unique()}")

col name Education : ['High School' 'PhD' 'Bachelor' 'Master']
col name PerformanceLevel : ['Low' 'Medium' 'High']
col name JobRole : ['Manager' 'Engineer' 'Consultant' 'Analyst']
col name City : ['Bangalore' 'Hyderabad' 'Chennai' 'Mumbai']
col name Department : ['HR' 'IT' 'Finance' 'Sales']

In [25]:
df['Education'].value_counts()

Education
Master         261
Bachelor       260
PhD            248
High School    231
Name: count, dtype: int64

In [38]:
# import the label encoder
from sklearn.preprocessing import LabelEncoder
LE = LabelEncoder()
# or LE = LabelEncoder()

In [39]:
#apply label encoder on categorical columns
for cat in cat_cols:
    df[cat] = LE.fit_transform(df[cat])

In [40]:
df.head()

,Age,Salary,Experience,ProjectsCompleted,WorkHours,Education,PerformanceLevel,JobRole,City,Department,Label
0,27,123337,15,9,9.7,1,1,3,0,1,0
1,26,81732,8,2,7.7,1,2,2,0,2,0
2,22,129391,5,7,4.2,3,0,2,2,1,1
3,56,112164,16,16,6.6,3,0,1,1,0,1
4,40,74316,4,29,4.6,0,0,3,3,1,1

## Onehot Encoding

In [50]:
data = read_csv('encoding.csv')

In [51]:
categorical_columns = data.select_dtypes(include='object').columns

In [57]:
# import the label encoder
from sklearn.preprocessing import OneHotEncoder
import pandas as pd
OHE = OneHotEncoder()
#apply label encoder on categorical columns

encoded_data = OHE.fit_transform(data[categorical_columns])

encoded_data
encoded_df = pd.DataFrame(encoded_data.toarray(),columns=OHE.get_feature_names_out(categorical_columns))

In [58]:
encoded_df

,Education_Bachelor,Education_High School,Education_Master,Education_PhD,PerformanceLevel_High,PerformanceLevel_Low,PerformanceLevel_Medium,JobRole_Analyst,JobRole_Consultant,JobRole_Engineer,JobRole_Manager,City_Bangalore,City_Chennai,City_Hyderabad,City_Mumbai,Department_Finance,Department_HR,Department_IT,Department_Sales
0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
3,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
4,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
996,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
997,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
998,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
999,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0

In [60]:
# convert into integer type
encoded_df = encoded_df.astype(int)
encoded_df

,Education_Bachelor,Education_High School,Education_Master,Education_PhD,PerformanceLevel_High,PerformanceLevel_Low,PerformanceLevel_Medium,JobRole_Analyst,JobRole_Consultant,JobRole_Engineer,JobRole_Manager,City_Bangalore,City_Chennai,City_Hyderabad,City_Mumbai,Department_Finance,Department_HR,Department_IT,Department_Sales
0,0,1,0,0,0,1,0,0,0,0,1,1,0,0,0,0,1,0,0
1,0,1,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,1,0
2,0,0,0,1,1,0,0,0,0,1,0,0,0,1,0,0,1,0,0
3,0,0,0,1,1,0,0,0,1,0,0,0,1,0,0,1,0,0,0
4,1,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,0,0,0,1,0,1,0,0,0,0,1,0,0,1,0,0,1,0,0
996,1,0,0,0,1,0,0,0,0,0,1,0,1,0,0,1,0,0,0
997,0,0,1,0,0,1,0,0,0,0,1,1,0,0,0,0,0,1,0
998,1,0,0,0,0,1,0,0,1,0,0,0,0,0,1,1,0,0,0
999,0,1,0,0,0,0,1,0,0,1,0,0,0,0,1,1,0,0,0

In [61]:
# concatinate the encoded data frame 

# Before concatinate the data drop the categorical columns sinc we had new encoded columns
df.drop(columns=categorical_columns)

     Age  Salary  Experience  ProjectsCompleted  WorkHours  Label
0     27  123337          15                  9        9.7      0
1     26   81732           8                  2        7.7      0
2     22  129391           5                  7        4.2      1
3     56  112164          16                 16        6.6      1
4     40   74316           4                 29        4.6      1
..   ...     ...         ...                ...        ...    ...
995   26  145382          23                 42       11.8      0
996   27  101500           1                 13        4.4      1
997   36  109391          19                 34        7.8      0
998   29  113448           1                 24       11.3      0
999   36   34326           0                 20        7.3      0

[1000 rows x 6 columns]

In [65]:
Final_DF = pd.concat([df,encoded_df],axis=1)

In [66]:
Final_DF

,Age,Salary,Experience,ProjectsCompleted,WorkHours,Education,PerformanceLevel,JobRole,City,Department,...,JobRole_Engineer,JobRole_Manager,City_Bangalore,City_Chennai,City_Hyderabad,City_Mumbai,Department_Finance,Department_HR,Department_IT,Department_Sales
0,27,123337,15,9,9.7,1,1,3,0,1,...,0,1,1,0,0,0,0,1,0,0
1,26,81732,8,2,7.7,1,2,2,0,2,...,1,0,1,0,0,0,0,0,1,0
2,22,129391,5,7,4.2,3,0,2,2,1,...,1,0,0,0,1,0,0,1,0,0
3,56,112164,16,16,6.6,3,0,1,1,0,...,0,0,0,1,0,0,1,0,0,0
4,40,74316,4,29,4.6,0,0,3,3,1,...,0,1,0,0,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,26,145382,23,42,11.8,3,1,3,2,1,...,0,1,0,0,1,0,0,1,0,0
996,27,101500,1,13,4.4,0,0,3,1,0,...,0,1,0,1,0,0,1,0,0,0
997,36,109391,19,34,7.8,2,1,3,0,2,...,0,1,1,0,0,0,0,0,1,0
998,29,113448,1,24,11.3,0,1,1,3,0,...,0,0,0,0,0,1,1,0,0,0
999,36,34326,0,20,7.3,1,2,2,3,0,...,1,0,0,0,0,1,1,0,0,0